default: &default
  adapter: postgresql

development:
  <<: *default
  host: localhost
  username: parlo
  password: placeholder
  database: parlo
  port: 5432

test:
  <<: *default
  url: <%= ENV['DATABASE_TEST_URL'] %>

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch('DATABASE_POOL', 10) %>
  prepared_statements: <%= ENV.fetch('DATABASE_PREPARED_STATEMENTS', true) %>
